import '../../../../global_imports.dart';

extension AuthMapper on AuthUserModel {
  AuthEntity toEntity() =>
      AuthEntity(
        id: id,
        firstName: firstName,
        secondName: secondName,
        thirdName: thirdName,
        lastName: lastName,
        slug: slug,
        email: email,
        locationId: locationId,
        verificationCode: verificationCode,
        userVerified: userVerified,
        packageExpiry: packageExpiry,
        createdAt: createdAt,
        updatedAt: updatedAt,
        dateOfBirth: dateOfBirth,
        phoneNumber: phoneNumber,
        patientCardNumber: patientCardNumber,
        nationalNumber: nationalNumber,
        secretaryId: secretaryId,
        receptionistId: receptionistId,
        medicalBillerId: medicalBillerId,
        weight: weight,
        height: height,
        occupation: occupation,
        payment: payment,
        gender: gender,
        refferal: refferal,
        profilePic: profilePic,
        physiotherapistId: physiotherapistId,
        dbName: dbName,
        dbUsername: dbUsername,
        dbPassword: dbPassword,
        hospitalId: hospitalId,
        isErp: isErp,
        medicalType: medicalType,
        patientErpId: patientErpId,
        tpaId: tpaId,
        fullName: fullName,
      );
}

extension AuthEntityMapper on AuthEntity {
  AuthUserModel toModel() =>
      AuthUserModel(
        id: id,
        firstName: firstName,
        secondName: secondName,
        thirdName: thirdName,
        lastName: lastName,
        slug: slug,
        email: email,
        locationId: locationId,
        verificationCode: verificationCode,
        userVerified: userVerified,
        packageExpiry: packageExpiry,
        createdAt: createdAt,
        updatedAt: updatedAt,
        dateOfBirth: dateOfBirth,
        phoneNumber: phoneNumber,
        patientCardNumber: patientCardNumber,
        nationalNumber: nationalNumber,
        secretaryId: secretaryId,
        receptionistId: receptionistId,
        medicalBillerId: medicalBillerId,
        weight: weight,
        height: height,
        occupation: occupation,
        payment: payment,
        gender: gender,
        refferal: refferal,
        profilePic: profilePic,
        physiotherapistId: physiotherapistId,
        dbName: dbName,
        dbUsername: dbUsername,
        dbPassword: dbPassword,
        hospitalId: hospitalId,
        isErp: isErp,
        medicalType: medicalType,
        patientErpId: patientErpId,
        tpaId: tpaId,
        fullName: fullName,
      );
}
